### PR TITLE
Bug fixes and Improvements

### PR DESCRIPTION
**Pull request by ItIsUday**

### CODE REVIEW

**Comment by Darshan-AS** [comment]
Can you also add a README.md file?

**Review by Darshan-AS — APPROVED** [review]
Looks Great. Thanks, brother mine!

**Comment by ItIsUday** [comment]
> Looks Great. Thanks, brother mine!
Muahahahaha

**Comment by ItIsUday** [comment]
> Looks Great. Thanks, brother mine!

Muahahahahah

**Pull request merged**
